---
project_name: giant recommand
service_name: giant-recommand
archive_file_path: giant-recommend-server/target
archive_file_name: giant-recommend-server-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: giant-recommend-server

#Jinja2 template vars
j2_java_home: "{{ JAVA7_HOME }}"
j2_process_name: com.kom.giant.recommend.server.StartRecommendServer
j2_service_name: "{{ service_name }}"

j2_zk_ip: "{{ ZK_DNS }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_elastic_ip: "{{ ELASTIC_IP }}"
j2_elastic_port: "{{ ELASTIC_PORT }}"
j2_elastic_name: "{{ ELASTIC_SEARCH_NAME }}"

j2_mysql_dns: "{{ MYSQL_99_IP }}"
j2_mysql_port: "{{ MYSQL_99_PORT }}"
j2_mysql_user: "{{ MYSQL_99_USERNAME1 }}"
j2_mysql_passwd: "{{ MYSQL_99_PASSWD1 }}"

j2_redis_ip: "{{ REDIS_IP }}"
j2_redis_port: "{{ REDIS_PORT }}"
j2_redis_passwd: "{{ REDIS_PASSWD1 }}"

config_list:
  - dubbo
  - elasticsearch
  - jdbc
  - redis