---
project_name: phoenix yop server
service_name: phoenix-yop-server
archive_file_path: phoenix-yop-server/target
archive_file_name: phoenix-yop-server-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: phoenix-yop-server

#Jinja2 template vars
j2_java_home: "{{ JAVA7_HOME }}"
j2_process_name: com.kom.phoenix.yop.app.server.ServerStart
j2_service_name: "{{ service_name }}"

j2_zk_dns1: "{{ ZK_DNS1 }}"
j2_zk_dns2: "{{ ZK_DNS2 }}"
j2_zk_dns3: "{{ ZK_DNS3 }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_mysql_dns: "{{ MYSQL_MASTER_DNS }}"
j2_mysql_port: "{{ MYSQL_PORT }}"
j2_mysql_user: "{{ MYSQL_MASTER_USERNAME }}"
j2_mysql_passwd: "{{ MYSQL_MASTER_PASSWD }}"

config_list:
  - dubbo
  - jdbc


