---
project_name: phoenix pontoon
service_name: phoenix-pontoon
archive_file_path: phoenix-pontoon-app/phoenix-pontoon-app-thrift-server/target
archive_file_name: phoenix-pontoon-app-thrift-server-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: phoenix-pontoon-app-thrift-server

#Jinja2 template vars
j2_java_home: "{{ JAVA7_HOME }}"
j2_process_name: com.kom.phoenix.pontoon.app.thrift.server.ServerStart
j2_service_name: "{{ service_name }}"

j2_zk_ip: "{{ ZK_DNS }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_mysql_dns: "{{ MYSQL_SLAVE_DNS }}"
j2_mysql_port: "{{ MYSQL_PORT }}"
j2_mysql_user: "{{ MYSQL_SLAVE_USERNAME }}"
j2_mysql_passwd: "{{ MYSQL_SLAVE_PASSWD }}"

j2_thrift_ip: "{{ THRIFT_IP0 }}"
j2_thrift_port: "{{ THRIFT_PORT02 }}"

config_list:
  - dubbo
  - jdbc
  - pontoon
  - thrift-item

