---
project_name: phoenix item
service_name: phoenix-item
archive_file_path: phoenix-item-app/phoenix-item-app-thrift-server/target
archive_file_name: phoenix-item-app-thrift-server-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: phoenix-item-app-thrift-server

#Jinja2 template vars
j2_java_home: "{{ JAVA7_HOME }}"
j2_process_name: com.kom.phoenix.item.app.thrift.server.ServerStart
j2_service_name: "{{ service_name }}"

j2_zk_dns1: "{{ ZK_DNS1 }}"
j2_zk_dns2: "{{ ZK_DNS2 }}"
j2_zk_dns3: "{{ ZK_DNS3 }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_mysql_dns: "{{ MYSQL_MASTER_DNS }}"
j2_mysql_port: "{{ MYSQL_PORT }}"
j2_mysql_user: "{{ MYSQL_MASTER_USERNAME }}"
j2_mysql_passwd: "{{ MYSQL_MASTER_PASSWD }}"

j2_mysql_slave_dns: "{{ MYSQL_SLAVE_DNS }}"
j2_mysql_slave_port: "{{ MYSQL_PORT }}"
j2_mysql_slave_user: "{{ MYSQL_SLAVE_USERNAME1 }}"
j2_mysql_slave_passwd: "{{ MYSQL_SLAVE_PASSWD1 }}"

j2_mysql_114_dns: "{{ MYSQL_114_DNS }}"
j2_mysql_114_port: "{{ MYSQL_114_PORT }}"
j2_mysql_114_user: "{{ MYSQL_114_USERNAME1 }}"
j2_mysql_114_passwd: "{{ MYSQL_114_PASSWD1 }}"

j2_thrift_ip: "{{ THRIFT_IP3 }}"
j2_thrift_port: "{{ THRIFT_PORT31 }}"

j2_elastic_ip1: "{{ ELASTIC_IP1 }}"
j2_elastic_ip2: "{{ ELASTIC_IP2 }}"
j2_elastic_port: "{{ ELASTIC_PORT }}"
j2_elastic_name: "{{ ELASTIC_NAME_SEARCH1 }}"

j2_kafka_dns: "{{ KAFKA_DNS }}"
j2_kafka_port: "{{ KAFKA_PORT }}"

config_list:
  - dubbo
  - data-giant-recommend-thrift
  - elasticsearch
  - jdbc