---
project_name: phoenix new b2b gateway dubbo service
service_name: phoenix-gateway-dubbo
archive_file_path: startup/target
archive_file_name: phoenix-ec-gateway.tar.gz


#Jinja2 template vars
j2_java_home: "{{ JAVA8_HOME }}"
j2_process_name: com.kom.phoenix.ec.gateway.startup.ThriftGatewayStartup
j2_service_name: "{{ service_name }}"

j2_zk_dns1: "{{ ZK_DNS1 }}"
j2_zk_dns2: "{{ ZK_DNS2 }}"
j2_zk_dns3: "{{ ZK_DNS3 }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_thrift_host: "{{ THRIFT_HOST }}"
j2_thrift_port: "{{ THRIFT_PORT01 }}"

config_list:
  - dubbo
  - thriftClient

