---
- name: test path
  command: pwd
  register: patt

- debug:
   msg: "{{patt}}"

#- name: custom server xml config modify HTTP Connector {{APP_LOCATION}}/{{ TOMCAT_CONF_NAME }}/{{ SERVER_XML }}
#  replace:
#    path: /home/uj/workspaces/devops/ansible/tomcat/groundhog/conf/server.xml
#    regexp: 'redirectPort="(\d+)" />'
#    replace: 'redirectPort="\1" URIEncoding="UTF-8" />'

#- name: custom config {{APP_LOCATION}}/{{ TOMCAT_CONF_NAME }}/{{ WEB_XML }}
#  blockinfile:
#    path: "{{APP_LOCATION}}/{{ TOMCAT_CONF_NAME }}/{{ WEB_XML }}"
#    insertbefore: "Default Session Configuration"
#    content: |
#      <filter>
#        <filter-name>CorsFilter</filter-name>
#        <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
#          <init-param>
#            <param-name>cors.allowed.headers</param-name>
#            <param-value>Content-Type,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,version,appId,token</param-value>
#           </init-param>
#      </filter>
#      <filter-mapping>
#        <filter-name>CorsFilter</filter-name>
#        <url-pattern>/*</url-pattern>
#      </filter-mapping>