---
project_name: phoenix item
service_name: phoenix-item
archive_file_path: phoenix-item-app/phoenix-item-app-thrift-server/target
archive_file_name: phoenix-item-app-thrift-server-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: phoenix-item-app-thrift-server

#Jinja2 template vars
j2_java_home: "{{ JAVA7_HOME }}"
j2_process_name: com.kom.phoenix.item.app.thrift.server.ServerStart
j2_service_name: "{{ service_name }}"

j2_zk_ip: "{{ ZK_DNS }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_mysql_dns: "{{ MYSQL_MASTER_DNS }}"
j2_mysql_port: "{{ MYSQL_PORT }}"
j2_mysql_user: "{{ MYSQL_MASTER_USERNAME1 }}"
j2_mysql_passwd: "{{ MYSQL_MASTER_PASSWD1 }}"

j2_thrift_ip: "{{ THRIFT_IP1 }}"
j2_thrift_port: "{{ THRIFT_PORT11 }}"

j2_elastic_ip: "{{ ELASTIC_IP }}"
j2_elastic_port: "{{ ELASTIC_PORT }}"
j2_elastic_name: "{{ ELASTIC_SEARCH_NAME }}"

j2_kafka_dns: "{{ KAFKA_DNS }}"
j2_kafka_port: "{{ KAFKA_PORT }}"

config_list:
  - dubbo
  - data-giant-recommend-thrift
  - elasticsearch
  - jdbc
  - kafka

