---
app_full_name: giant report
app_name: giant-report
process_name: "{{ APP_LOCATION }}"
archive_file_path: giant-report-app/giant-report-app-report/giant-report-app-report-web/target
archive_file_name: giant-report-app-report-web-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: report


#conf/server.xml
tomcat_shutdown_port: 8081
tomcat_connector_http_port: 8080
tomcat_connector_ajp_port: 8082

doc_path: ""
doc_base: report

j2_java_home: "{{ JAVA7_HOME }}"

j2_zk_ip: "{{ ZK_DNS }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_mysql_dns: "{{ MYSQL_99_IP }}"
j2_mysql_port: "{{ MYSQL_99_PORT }}"
j2_mysql_user: "{{ MYSQL_99_USERNAME1 }}"
j2_mysql_passwd: "{{ MYSQL_99_PASSWD1 }}"

j2_mysql_data_stage_ip: "{{ MYSQL_DATA_STAGE_IP }}"
j2_mysql_data_stage_port: "{{ MYSQL_DATA_STAGE_PORT }}"
j2_mysql_data_stage_user: "{{ MYSQL_DATA_STAGE_USERNAME1 }}"
j2_mysql_data_stage_passwd: "{{ MYSQL_DATA_STAGE_PASSWD1 }}"


j2_redis_ip: "{{ REDIS_IP }}"
j2_redis_port: "{{ REDIS_PORT }}"
j2_redis_passwd: "{{ REDIS_PASSWD1 }}"

config_list:
  - jdbc
  - jdbc_report
  - dubbo
  - redis

