---
app_full_name: zhong chuang kong jian
app_name: phoenix-webapp-boss
process_name: "{{ APP_LOCATION }}"
archive_file_path: phoenix-webapp-web/phoenix-webapp-web-boss/target
archive_file_name: phoenix-webapp-web-boss-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: boss

j2_java_home: "{{ JAVA8_HOME }}"

#conf/server.xml
tomcat_shutdown_port: 8381
tomcat_connector_http_port: 8380
tomcat_connector_ajp_port: 8382

j2_zk_dns: "{{ ZK_DNS }}"
j2_zk_port: "{{ ZK_PORT }}"

config_list:
  - dubbo

