---
project_name: groundhog product service
service_name: groundhog-product
archive_file_path: groundhog-product-server/groundhog-product-server-app/target
archive_file_name: groundhog-product-server-app-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: groundhog-product-server-app


#Jinja2 template vars
j2_java_home: "{{ JAVA8_HOME }}"
j2_process_name: com.pharmaking.groundhog.product.server.app.StartProductAppServer
j2_service_name: "{{ service_name }}"

j2_zk_dns1: "{{ ZK_DNS1 }}"
j2_zk_dns2: "{{ ZK_DNS2 }}"
j2_zk_dns3: "{{ ZK_DNS3 }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_elastic_name: "{{ ELASTIC_NAME_SEARCH }}"
j2_elastic_dns1: "{{ ELASTIC_DNS1 }}"
j2_elastic_dns2: "{{ ELASTIC_DNS2 }}"
j2_elastic_port: "{{ ELASTIC_PORT }}"

j2_mysql_dns: "{{ MYSQL_MASTER_DNS }}"
j2_mysql_port: "{{ MYSQL_PORT }}"
j2_mysql_user: "{{ MYSQL_MASTER_USERNAME }}"
j2_mysql_passwd: "{{ MYSQL_MASTER_PASSWD }}"

config_list:
  - dubbo
  - elasticsearch
  - jdbc


