---
- name: add context under host tag in conf/server.xml
  blockinfile:
    path: "{{APP_LOCATION}}/{{ TOMCAT_CONF_NAME }}/{{ SERVER_XML }}"
    insertafter: "unpackWARs=\"true\" autoDeploy=\"true\">"
    content: |
      <Context path="{{ doc_path }}"
                 docBase="{{APP_LOCATION}}/{{ TOMCAT_WEBAPPS_NAME }}/{{doc_base}}"
                 crossContext="true"
                 debug="0"
                 reloadable="true"
                 trusted="false" >
        </Context>