---

- name: modify three ports in {{ APP_LOCATION }}/conf/server.xml
  replace:
    path: "{{APP_LOCATION}}/{{ TOMCAT_CONF_NAME }}/{{ SERVER_XML }}"
    regexp: '<Server port="\d+" shutdown="SHUTDOWN">'
    replace: '<Server port="{{ tomcat_shutdown_port }}" shutdown="SHUTDOWN">'

- replace:
    path: "{{APP_LOCATION}}/{{ TOMCAT_CONF_NAME }}/{{ SERVER_XML }}"
    regexp: '<Connector port="\d+" protocol="HTTP/1.1"'
    replace: '<Connector port="{{ tomcat_connector_http_port }}" protocol="HTTP/1.1"'

- replace:
    path: "{{APP_LOCATION}}/{{ TOMCAT_CONF_NAME }}/{{ SERVER_XML }}"
    regexp: '<Connector port="\d+" protocol="AJP/1.3"'
    replace: '<Connector port="{{ tomcat_connector_ajp_port }}" protocol="AJP/1.3"'