---
project_name: groundhog product sync service
service_name: groundhog-product-sync
archive_file_path: groundhog-product-server/groundhog-product-server-sync/target
archive_file_name: groundhog-product-server-sync-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: groundhog-product-server-sync

#Jinja2 template vars
j2_java_home: "{{ JAVA8_HOME }}"

j2_process_name: com.pharmaking.groundhog.product.server.sync.StartProductSyncServer
j2_full_process_name: com.pharmaking.groundhog.product.server.sync.FullProductSyncServer
j2_service_name: "{{ service_name }}"

j2_kafka_dns1: "{{ KAFKA_DNS1 }}"
j2_kafka_dns2: "{{ KAFKA_DNS2 }}"
j2_kafka_dns3: "{{ KAFKA_DNS3 }}"
j2_kafka_port: "{{ KAFKA_PORT }}"

j2_elastic_name: "{{ ELASTIC_NAME_SEARCH }}"
j2_elastic_dns1: "{{ ELASTIC_DNS1 }}"
j2_elastic_dns2: "{{ ELASTIC_DNS2 }}"
j2_elastic_port: "{{ ELASTIC_PORT }}"

j2_mysql_dns: "{{ MYSQL_MASTER_DNS }}"
j2_mysql_port: "{{ MYSQL_PORT }}"
j2_mysql_user: "{{ MYSQL_MASTER_USERNAME }}"
j2_mysql_passwd: "{{ MYSQL_MASTER_PASSWD }}"

config_list:
  - kafka
  - elasticsearch
  - jdbc


