---
project_name: phoenix new b2b gateway dubbo service
service_name: phoenix-gateway-dubbo
archive_file_path: startup/target
archive_file_name: phoenix-ec-gateway.tar.gz


#Jinja2 template vars
j2_java_home: "{{ JAVA7_HOME }}"
j2_process_name: com.kom.phoenix.ec.gateway.startup.ThriftGatewayStartup
j2_service_name: "{{ service_name }}"

j2_zk_ip: "{{ ZK_IP }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_thrift_ip: "{{ THRIFT_IP0 }}"
j2_thrift_port: "{{ THRIFT_PORT01 }}"

config_list:
  - dubbo
  - thriftClient

