---
project_name:  phoenix pipe hos sync
service_name:  phoenix-pipe-host-sync
archive_file_path: phoenix-pipe-host/phoenix-pipe-host-sync/target
archive_file_name: phoenix-pipe-host-sync-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: phoenix-pipe-host-sync

#Jinja2 template vars
j2_java_home: "{{ JAVA8_HOME }}"
j2_process_name: com.kom.phoenix.pipe.host.sync.server.ServerStart
j2_service_name: "{{ service_name }}"

j2_zk_dns: "{{ ZK_DNS }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_redis_host: "{{ REDIS_HOST }}"
j2_redis_port: "{{ REDIS_PORT }}"
j2_redis_passwd: "{{ REDIS_PASSWD }}"

j2_mysql_dns: "{{ MYSQL_MASTER_DNS }}"
j2_mysql_port: "{{ MYSQL_PORT }}"
j2_mysql_user: "{{ MYSQL_MASTER_USERNAME1 }}"
j2_mysql_passwd: "{{ MYSQL_MASTER_PASSWD1 }}"

j2_kafka_dns: "{{ KAFKA_DNS }}"
j2_kafka_port: "{{ KAFKA_PORT }}"

config_list:
  - jdbc
  - dubbo
  - kafka
  - redis


