---
app_full_name: repairman tools
app_name: repairman-tools
process_name: "{{ APP_LOCATION }}"
archive_file_path: repairman-tools-web/target
archive_file_name: repairman-tools-web.tar.gz
unarchive_file_name: repairman


#conf/server.xml
tomcat_shutdown_port: 8781
tomcat_connector_http_port: 8780
tomcat_connector_ajp_port: 8782

doc_path: /
doc_base: repairman

j2_java_home: "{{ JAVA8_HOME }}"

j2_zk_ip: "{{ ZK_IP }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_mysql_dns: "{{ MYSQL_SLAVE_DNS }}"
j2_mysql_port: "{{ MYSQL_PORT }}"
j2_mysql_user: "{{ MYSQL_SLAVE_USERNAME }}"
j2_mysql_passwd: "{{ MYSQL_SLAVE_PASSWD }}"

j2_mysql_yaoyi_dns: "{{ MYSQL_YAOYI_DNS }}"
j2_mysql_yaoyi_port: "{{ MYSQL_YAOYI_PORT }}"
j2_mysql_yaoyi_user: "{{ MYSQL_YAOYI_USERNAME }}"
j2_mysql_yaoyi_passwd: "{{ MYSQL_YAOYI_PASSWD }}"


config_list:
  - application
  - dubbo
  - jdbc
