---
project_name: giant recommand
service_name: giant-recommand
archive_file_path: giant-recommend-server/target
archive_file_name: giant-recommend-server-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: giant-recommend-server

#Jinja2 template vars
j2_java_home: "{{ JAVA7_HOME }}"
j2_process_name: com.kom.giant.recommend.server.StartRecommendServer
j2_service_name: "{{ service_name }}"

j2_zk_dns1: "{{ ZK_DNS1 }}"
j2_zk_dns2: "{{ ZK_DNS2 }}"
j2_zk_dns3: "{{ ZK_DNS3 }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_elastic_name: "{{ ELASTIC_NAME_SEARCH }}"
j2_elastic_dns1: "{{ ELASTIC_DNS1 }}"
j2_elastic_dns2: "{{ ELASTIC_DNS2 }}"
j2_elastic_port: "{{ ELASTIC_PORT }}"

j2_mysql_dns: "{{ MYSQL_114_IP }}"
j2_mysql_port: "{{ MYSQL_114_PORT }}"
j2_mysql_user: "{{ MYSQL_114_USERNAME }}"
j2_mysql_passwd: "{{ MYSQL_114_PASSWD }}"

j2_redis_host: "{{ REDIS_HOST }}"
j2_redis_port: "{{ REDIS_PORT }}"
j2_redis_passwd: "{{ REDIS_PASSWD }}"

config_list:
  - dubbo
  - elasticsearch
  - jdbc
  - redis
  - thrift-recommend
  - envir-config

