---
project_name: giant search product server sync
service_name: giant-search-product-server-sync
archive_file_path: giant-search-product-server/giant-search-product-server-sync/target
archive_file_name: giant-search-product-server-sync-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: giant-search-product-server-sync


#Jinja2 template vars
j2_java_home: "{{ JAVA8_HOME }}"
j2_process_name: com.kom.giant.search.product.server.sync.StartProductSearchSync
j2_service_name: "{{ service_name }}"

j2_zk_dns: "{{ ZK_DNS }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_elastic_ip: "{{ ELASTIC_IP }}"
j2_elastic_port: "{{ ELASTIC_PORT }}"
j2_elastic_name: "{{ ELASTIC_SEARCH_NAME }}"

j2_mysql_dns: "{{ MYSQL_SLAVE_DNS }}"
j2_mysql_port: "{{ MYSQL_PORT }}"
j2_mysql_user: "{{ MYSQL_SLAVE_USERNAME }}"
j2_mysql_passwd: "{{ MYSQL_SLAVE_PASSWD }}"

j2_kafka_dns: "{{ KAFKA_DNS }}"
j2_kafka_port: "{{ KAFKA_PORT }}"

config_list:
  - dubbo
  - elasticsearch
  - jdbc
  - kafka


