---
app_full_name: phoenix pipe console
app_name: phoenix-pipe-console
process_name: "{{ APP_LOCATION }}"
archive_file_path: phoenix-pipe-web/phoenix-pipe-web-console/phoenix-pipe-web-console-portal/target
archive_file_name: phoenix-pipe-web-console-portal-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: console

doc_path: console
doc_base: console

j2_java_home: "{{ JAVA8_HOME }}"

tomcat_shutdown_port: 8021
tomcat_connector_http_port: 8020
tomcat_connector_ajp_port: 8022

j2_redis_host: "{{ REDIS_HOST }}"
j2_redis_port: "{{ REDIS_PORT }}"
j2_redis_passwd: "{{ REDIS_PASSWD }}"

j2_zk_dns1: "{{ ZK_DNS1 }}"
j2_zk_dns2: "{{ ZK_DNS2 }}"
j2_zk_dns3: "{{ ZK_DNS3 }}"
j2_zk_port: "{{ ZK_PORT }}"

config_list:
  - redis
  - dubbo
  - kafka