---
project_name:  phoenix pipe hos admin
service_name:  phoenix-pipe-host-admin
archive_file_path: phoenix-pipe-host/phoenix-pipe-host-admin/target
archive_file_name: phoenix-pipe-host-admin-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: phoenix-pipe-host-admin

jenkins_name: phoenix-pipe-admin

#Jinja2 template vars
j2_java_home: "{{ JAVA8_HOME }}"
j2_process_name: com.kom.phoenix.pipe.host.admin.server.ServerStart
j2_service_name: "{{ service_name }}"

j2_zk_dns1: "{{ ZK_DNS1 }}"
j2_zk_dns2: "{{ ZK_DNS2 }}"
j2_zk_dns3: "{{ ZK_DNS3 }}"
j2_zk_port: "{{ ZK_PORT }}"

j2_redis_host: "{{ REDIS_HOST }}"
j2_redis_port: "{{ REDIS_PORT }}"
j2_redis_passwd: "{{ REDIS_PASSWD }}"

j2_mysql_pipe_dns: "{{ MYSQL_PIPE_DNS }}"
j2_mysql_pipe_user: "{{ MYSQL_PIPE_USERNAME }}"
j2_mysql_pipe_passwd: "{{ MYSQL_PIPE_PASSWD }}"
j2_mysql_port: "{{ MYSQL_PORT }}"

j2_mysql_slave_dns: "{{ MYSQL_SLAVE_DNS }}"
j2_mysql_slave_user: "{{ MYSQL_SLAVE_USERNAME }}"
j2_mysql_slave_passwd: "{{ MYSQL_SLAVE_PASSWD }}"

j2_kafka_dns1: "{{ KAFKA_DNS1 }}"
j2_kafka_dns2: "{{ KAFKA_DNS2 }}"
j2_kafka_dns3: "{{ KAFKA_DNS3 }}"
j2_kafka_port: "{{ KAFKA_PORT }}"

config_list:
  - jdbc
  - dubbo
  - kafka
  - redis


