---
project_name: giant realtime server
service_name: giant-realtime-server
archive_file_path: giant-realtime-server/target
archive_file_name: giant-realtime-server-1.0.0-SNAPSHOT.tar.gz
unarchive_file_name: giant-realtime-server

#Jinja2 template vars
j2_java_home: "{{ JAVA8_HOME }}"
j2_process_name: com.kom.giant.realtime.server.StartRealtimeServer
j2_service_name: "{{ service_name }}"

j2_mysql_slave_ip: "{{ MYSQL_SLAVE_IP }}"
j2_mysql_slave_port: "{{ MYSQL_PORT }}"
j2_mysql_slave_user: "{{ MYSQL_SLAVE_USERNAME }}"
j2_mysql_slave_passwd: "{{ MYSQL_SLAVE_PASSWD }}"

j2_mysql_data_stage_ip: "{{ MYSQL_DATA_STAGE_IP }}"
j2_mysql_data_stage_port: "{{ MYSQL_DATA_STAGE_PORT }}"
j2_mysql_data_stage_user: "{{ MYSQL_DATA_STAGE_USERNAME }}"
j2_mysql_data_stage_passwd: "{{ MYSQL_DATA_STAGE_PASSWD }}"


j2_kafka_dns: "{{ KAFKA_DNS }}"
j2_kafka_port: "{{ KAFKA_PORT }}"

config_list:
  - jdbc
  - kafka

